title: "Just Summaries – No Filler"
description: "Minimal words, maximum understanding."
theme: jekyll-theme-minimal
baseurl: "/summaries"  # This ensures correct post URLs
url: "https://adas2327.github.io"
show_excerpts: true
plugins:
  - jekyll-feed
mathjax: true

# Use custom head.html file (ensures MathJax is loaded in every page)
include:
  - _includes/head.html
