title: "Just Summaries – No Filler"
description: "Minimal words, maximum understanding."
theme: jekyll-theme-minimal
baseurl: "/summaries"  # This ensures correct post URLs
url: "https://adas2327.github.io"
show_excerpts: true
plugins:
  - jekyll-feed
markdown: kramdown
kramdown:
  input: GFM
defaults:
  - scope:
      path: "search.json.liquid"
      type: "pages"
    values:
      permalink: "/summaries/search.json"  # Ensure it follows the baseurl
include:
  - search.json.liquid  # Ensure it's included
# Trigger rebuild

