title: "Just Summaries – No Filler"
description: "Minimal words, maximum understanding."
theme: jekyll-theme-minimal
baseurl: "/summaries"  # This ensures correct post URLs
url: "https://adas2327.github.io"
show_excerpts: true
plugins:
  - jekyll-feed
markdown: kramdown
kramdown:
  input: GFM
include:
  - search.json
# Trigger rebuild
